### ISSUE TITLE
Link to another python module with optical material properties

### ISSUE THREAD

**Issue by FilipDominec** [jtambasco/opticalmaterialspy#1]
Hi, if you needed permittivity spectra for common optical materials, please take a look at https://github.com/FilipDominec/python-meep-utils/blob/master/meep_materials.py

In the referred file, the permittivity is composed as a sum of discrete Lorentzian oscillators, in which form the materials can be loaded to the MEEP FDTD simulation. (The exact material-loading routine is https://github.com/FilipDominec/python-meep-utils/blob/master/meep_utils.py#L211 )

The permittivity spectra can be compared with experimental data from many papers, see http://www.fzu.cz/~dominecf/eps/

Note also that there is another project trying to give easy access to optical constants on github: https://github.com/polyanskiy/refractiveindex.info-database

Regards, Filip

**Comment by jtambasco** [comment]
I don't think this is an issue, more a comment...
