### ISSUE TITLE
Installing with PIP, and refractive index info does not work

### ISSUE THREAD

**Issue by cbuhl** [jtambasco/opticalmaterialspy#2]
Installing with "pip install opticalmaterialspy", and that went fine. The version installed is 0.20, which is also reflected on the python packaging index. 

But I'm unable to get to the refractive index working. Do you have any idea what's up?
I'm not able to find the function anywhere, in the files. I might be doing something wrong. 

I'm really hoping to get this to work - it's highly desirable to have a consistent way of calling the optical parameters!

**Comment by jtambasco** [comment]
Hey,  I'm not really sure what you mean.  I just quickly tested install from pip and it worked fine.

Make sure you're using Python 3 (not Python 2)?

After installing it, you should be able to make a script with:
```
import opticalmaterialspy as mat

material = mat.SiO2()
print(material.n(1550))
```
and it should print the refractive index of SiO2.  If you want another material (replace `SiO2` in the above code), you can consult the [reference](http://opticalmaterialspy.readthedocs.io/en/latest/api.html#).

If you want to add your own material as it's not in the list, you need to create it, or you can find the website link and use the [RefractiveIndexWeb](http://opticalmaterialspy.readthedocs.io/en/latest/api/opticalmaterialspy.material.RefractiveIndexWeb.html#opticalmaterialspy.material.RefractiveIndexWeb) class as the `material`.

You shouldn't need interact with any of the installed opticalmaterialspy library; it'll go in the system directory and shouldn't be modified (othewise it'll mess up upgrades).

Please provide some more details about what exactly didn't work if you're still having trouble :)
